### PR TITLE
Test dataset of subsampled PacBio Hifi reads for assembly workflow

### PR DESCRIPTION
**Pull request by elizabethmcd**
This PR contains subsampled PacBio HiFi reads down to 100 reads and a samplesheet for use in the Arcadia-Science/assembly workflow. The decision to subsample down to only 100 reads was based on the size of the file at 2.5 MB, a subsampled file down to 1000 reads was 23 MB and I can change this later if 100 reads doesn't work.

### CODE REVIEW

**Review by taylorreiter — CHANGES_REQUESTED** [review]
I think the file should probably be gzipped unless you have a reason to not. Also do you think it makes sense to include two PacBio HiFi sequences to make sure the pipeline can run on multiple samples?

Also what is the origin of this file? Does it have an SRR accession number?

Do tests runs work locally with this subset?

Lastly, did you have the same sample sheet issues here as you're having in the metagenomics PR, or is that all worked out now?

**Comment by elizabethmcd** [comment]
- I will gzip the files 
- I think it would be great to have 2 HiFi sequences, we just don't have two separate HiFi experiments internally yet
- I don't think there is an SRR accession number for this, still working with Peter on this
- My approach thus far has been to first put the test dataset here and then test the test config in the pipeline, but you're right then that doesn't catch issues like with the samplesheet format before

**Comment by taylorreiter** [comment]
> * I will gzip the files

👍 
> * I think it would be great to have 2 HiFi sequences, we just don't have two separate HiFi experiments internally yet

can we use non-internal data to build it? or do you want to keep these all internal?

>  * I don't think there is an SRR accession number for this, still working with Peter on this

same as above, can we just use hifi data that's already on the SRA so it can all be fully documented and recorded now?

>  * My approach thus far has been to first put the test dataset here and then test the test config in the pipeline, but you're right then that doesn't catch issues like with the samplesheet format before

ya that makes sense -- very chicken eggish, we can roll with that process! These PRs are quick to review so I think that's easy enough to support.

**Comment by elizabethmcd** [comment]
I gzipped the test dataset and made some changes to the format so it conforms to the default input samplesheet format. I tested this with the assembly workflow and it gets past the `INPUT_SAMPLESHEET` check. I think for now I would like to stay with internal datasets and just update when we have another HiFi dataset since if there are issues I have direct people to ask. Unless there was prior PacBio HiFi done for some of the Dutton lab things that would be an easy publicly available alternative...

**Comment by elizabethmcd** [comment]
I'm going to go ahead and approve this so I can move forward with making additions to the assembly workflow with this test dataset and come back to these points with issues

**Pull request merged**
